apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    # Example htpasswd entries
    # Format: username:encrypted_password
    # Use: htpasswd -c -B htpasswd username
    # admin:$2y$10$example_encrypted_password_hash
    # user1:$2y$10$example_encrypted_password_hash

