{{- $globalEnabled := and .Values.global .Values.global.enabled }}
{{- if $globalEnabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.global.project }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  description: ArgoCD project for global configurations
  sourceRepos:
    - '{{ .Values.global.repoURL }}'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
{{- end }}
{{- range .Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .project }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  description: ArgoCD project for {{ .name }}
  sourceRepos:
    - '{{ .repoURL }}'
  destinations:
    - namespace: '*'
      name: {{ .destination }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
{{- end }}

